export const seedProducts = [
  {
    name: "Linear",
    description: "Streamline issues, projects, and product roadmaps. Built for high-performance teams.",
    category: "Project Management",
    url: "https://linear.app",
    pricing_url: "https://linear.app/pricing",
    min_price: 0,
    max_price: 12,
    pricing_model: "monthly" as const,
    pricing_details: "Free for small teams, $8/user/mo Standard, $12/user/mo Plus",
    logo_url: null
  },
  {
    name: "Vercel",
    description: "Deploy web projects with the best frontend developer experience and highest end user performance.",
    category: "Hosting & Deployment",
    url: "https://vercel.com",
    pricing_url: "https://vercel.com/pricing",
    min_price: 0,
    max_price: 20,
    pricing_model: "monthly" as const,
    pricing_details: "Free Hobby tier, $20/user/mo Pro tier",
    logo_url: null
  },
  {
    name: "Stripe",
    description: "Payment processing platform for internet businesses. Accept payments, send payouts, and manage business online.",
    category: "Payments",
    url: "https://stripe.com",
    pricing_url: "https://stripe.com/pricing",
    min_price: 0,
    max_price: null,
    pricing_model: "freemium" as const,
    pricing_details: "2.9% + 30¢ per successful card charge. No monthly fees.",
    logo_url: null
  },
  {
    name: "Resend",
    description: "Email API for developers. Build, test, and send transactional emails at scale.",
    category: "Email",
    url: "https://resend.com",
    pricing_url: "https://resend.com/pricing",
    min_price: 0,
    max_price: 20,
    pricing_model: "monthly" as const,
    pricing_details: "Free: 3,000 emails/mo. Pro: $20/mo for 50,000 emails",
    logo_url: null
  },
  {
    name: "Clerk",
    description: "Complete user management. Authentication, user profiles, and session management out of the box.",
    category: "Authentication",
    url: "https://clerk.com",
    pricing_url: "https://clerk.com/pricing",
    min_price: 0,
    max_price: 25,
    pricing_model: "monthly" as const,
    pricing_details: "Free: 10,000 MAUs. Pro: $25/mo + $0.02/MAU",
    logo_url: null
  },
  {
    name: "Supabase",
    description: "Open source Firebase alternative. Postgres database, authentication, instant APIs, and realtime subscriptions.",
    category: "Database",
    url: "https://supabase.com",
    pricing_url: "https://supabase.com/pricing",
    min_price: 0,
    max_price: 25,
    pricing_model: "monthly" as const,
    pricing_details: "Free tier included. Pro: $25/mo per project",
    logo_url: null
  },
  {
    name: "Plausible",
    description: "Simple, privacy-friendly Google Analytics alternative. No cookies, fully GDPR compliant.",
    category: "Analytics",
    url: "https://plausible.io",
    pricing_url: "https://plausible.io/pricing",
    min_price: 9,
    max_price: 19,
    pricing_model: "monthly" as const,
    pricing_details: "$9/mo for 10k pageviews, $19/mo for 100k pageviews",
    logo_url: null
  },
  {
    name: "Crisp",
    description: "All-in-one customer messaging platform. Live chat, chatbot, knowledge base, and CRM.",
    category: "Customer Support",
    url: "https://crisp.chat",
    pricing_url: "https://crisp.chat/en/pricing",
    min_price: 0,
    max_price: 25,
    pricing_model: "monthly" as const,
    pricing_details: "Free for 2 seats. Pro: $25/mo per workspace",
    logo_url: null
  },
  {
    name: "Lemon Squeezy",
    description: "All-in-one platform for selling digital products. Payments, tax compliance, and subscriptions.",
    category: "Payments",
    url: "https://lemonsqueezy.com",
    pricing_url: "https://lemonsqueezy.com/pricing",
    min_price: 0,
    max_price: null,
    pricing_model: "freemium" as const,
    pricing_details: "5% + 50¢ per transaction. Handles global taxes.",
    logo_url: null
  },
  {
    name: "Posthog",
    description: "Open source product analytics. Event tracking, session recording, feature flags, and A/B testing.",
    category: "Analytics",
    url: "https://posthog.com",
    pricing_url: "https://posthog.com/pricing",
    min_price: 0,
    max_price: null,
    pricing_model: "freemium" as const,
    pricing_details: "1M events/mo free. Then usage-based pricing.",
    logo_url: null
  },
  {
    name: "Notion",
    description: "All-in-one workspace for notes, docs, wikis, and project management.",
    category: "Project Management",
    url: "https://notion.so",
    pricing_url: "https://notion.so/pricing",
    min_price: 0,
    max_price: 10,
    pricing_model: "monthly" as const,
    pricing_details: "Free for personal use. Plus: $10/user/mo",
    logo_url: null
  },
  {
    name: "Tailwind UI",
    description: "Beautifully designed, expertly crafted components and templates for Tailwind CSS.",
    category: "UI Components",
    url: "https://tailwindui.com",
    pricing_url: "https://tailwindui.com/pricing",
    min_price: 149,
    max_price: 299,
    pricing_model: "one-time" as const,
    pricing_details: "$149 per package or $299 for all-access",
    logo_url: null
  },
  {
    name: "Neon",
    description: "Serverless Postgres. Branch your database like code. Scale to zero.",
    category: "Database",
    url: "https://neon.tech",
    pricing_url: "https://neon.tech/pricing",
    min_price: 0,
    max_price: 19,
    pricing_model: "monthly" as const,
    pricing_details: "Free tier with 512MB storage. Pro: $19/mo",
    logo_url: null
  },
  {
    name: "Fly.io",
    description: "Deploy app servers close to your users. Run full-stack apps and databases.",
    category: "Hosting & Deployment",
    url: "https://fly.io",
    pricing_url: "https://fly.io/pricing",
    min_price: 0,
    max_price: null,
    pricing_model: "freemium" as const,
    pricing_details: "Free allowances included. Pay for what you use.",
    logo_url: null
  },
  {
    name: "Railway",
    description: "Instant deployments, effortless scaling. Deploy databases, apps, and cron jobs.",
    category: "Hosting & Deployment",
    url: "https://railway.app",
    pricing_url: "https://railway.app/pricing",
    min_price: 0,
    max_price: 20,
    pricing_model: "monthly" as const,
    pricing_details: "Free $5/mo credits. Pro: $20/seat/mo",
    logo_url: null
  },
  {
    name: "Dub",
    description: "Open source link management for modern marketing teams. Short links with analytics.",
    category: "Marketing",
    url: "https://dub.co",
    pricing_url: "https://dub.co/pricing",
    min_price: 0,
    max_price: 24,
    pricing_model: "monthly" as const,
    pricing_details: "Free: 25 links/mo. Pro: $24/mo for 1,000 links",
    logo_url: null
  },
  {
    name: "Cal.com",
    description: "Open source scheduling infrastructure. Calendly alternative you can self-host.",
    category: "Scheduling",
    url: "https://cal.com",
    pricing_url: "https://cal.com/pricing",
    min_price: 0,
    max_price: 12,
    pricing_model: "monthly" as const,
    pricing_details: "Free forever for individuals. Team: $12/user/mo",
    logo_url: null
  },
  {
    name: "Buttondown",
    description: "The easiest way to run your newsletter. Simple, powerful, and affordable.",
    category: "Email",
    url: "https://buttondown.email",
    pricing_url: "https://buttondown.email/pricing",
    min_price: 0,
    max_price: 29,
    pricing_model: "monthly" as const,
    pricing_details: "Free: 100 subscribers. Basic: $9/mo. Pro: $29/mo",
    logo_url: null
  },
  {
    name: "Sentry",
    description: "Application monitoring platform. Error tracking, performance monitoring, and session replay.",
    category: "Monitoring",
    url: "https://sentry.io",
    pricing_url: "https://sentry.io/pricing",
    min_price: 0,
    max_price: 26,
    pricing_model: "monthly" as const,
    pricing_details: "Free: 5K errors/mo. Team: $26/mo for 50K events",
    logo_url: null
  },
  {
    name: "Loops",
    description: "Email for modern SaaS. Beautiful email campaigns and automations.",
    category: "Email",
    url: "https://loops.so",
    pricing_url: "https://loops.so/pricing",
    min_price: 0,
    max_price: 49,
    pricing_model: "monthly" as const,
    pricing_details: "Free: 1,000 contacts. Starter: $49/mo for 5,000 contacts",
    logo_url: null
  }
];
